laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index');

// Route::group(['middleware' => ['auth', 'role:super-admin,sub-admin']], function () {


Route::group(['namespace' => 'AdminPanel'], function () {

Route::post('/accounts/search', 'AccountsResource@search');
Route::resource('/accounts', 'AccountsResource');

Route::get('/visits/escalated', 'VisitControllerResource@getEscalated');
Route::post('/visits/status', 'VisitControllerResource@updateStatus')->name('visits.status');
Route::resource('/visits', 'VisitControllerResource');

Route::post('/catalogs/status', 'CatalogControllerResource@updateStatus')->name('catalogs.status');

Route::post('/categories/search', 'CategoriesControllerResource@search');
Route::resource('/categories', 'CategoriesControllerResource');

Route::post('/breeds/search', 'BreedControllerResource@search');
Route::resource('/breeds', 'BreedControllerResource');

Route::resource('/catalogs', 'CatalogControllerResource');
Route::resource('/contact-details', 'ContactDetailControllerResource');



});

Route::get('/{page}', 'HomeController@page');

// });

laravel/app/Http/Controllers/Api/AccountController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\AccountResource;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Request as Api;
use Spatie\Permission\Models\Role;
use Symfony\Component\HttpFoundation\Response;

use App\User;


class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $model = User::find(\Auth::user()->id);
      $response = new AccountResource($model);

      return response()->json($response, Response::HTTP_OK);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

     $user =  User::find($request->user()->id);

     $request->validate([
      'first_name' => "required|string|max:255",
      'last_name' => "required|string|max:255",
      'email' => "required|string|email|max:255",
    ]);

     /*
      * DECLARE ARRAY VARIABLE
      */

     $name = $request->first_name .' '. $request->last_name; 

     $details_array = array(
      'name' => $name,
      'email' => $request->email
    );
        /*
        *
        */

      /*
      * CHECK IF PASSWORD HAS INPUT
      */
      if($request->password != '') {

       $request->validate([
         'password' => "string|min:8",
       ]);   

       $password = array('password' => Hash::make($request->password));

       // PUSH PASSWORD INPUT TO ARRAY
       $merged_array = array_merge($details_array, $password);

     }
      /*
      * 
      */

      $user->userDetails()->updateOrCreate([], $request->all());

      DB::beginTransaction();

      try {

      /*
      * UPDATE RECORDS
      */
      $user->update($merged_array ?? $details_array);
      /*
      * 
      */

        /*
        *  CREATE ROLE IF NOT EXIST
        */ 
        if(!Role::whereName('client')->exists()) {

         $role = Role::create(['name' => 'client']);

       }
       /*
       *
       */

       /*
       *  UPDATE ROLE
       */
       $user->syncRoles('client');
        /*
       *
       */

       /*
       *  UPDATE PERMISSIONS
       */
       // if($request->role == 'super-admin') {

       //   $user->givePermissionTo(['view', 'create', 'edit' , 'remove']);          

       // } else {

       //   foreach ((Array)$request->permissions as $key => $value) {

       //    $value ? $user->givePermissionTo($key) : $user->revokePermissionTo($key);

       //  }

       $user->givePermissionTo(['view']);

       

     
      /*
       *
       */

      DB::commit();

      return response()->json(['success'=>'Data updated successfully'], Response::HTTP_OK); 

    } catch (Exception $e) {

      DB::rollback();

      return response()->json(['error' => $e->getMessage()], Response::HTTP_BAD_REQUEST);

    }

  }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
  }

laravel/resources/views/pages/accounts/create.blade.php
@extends('template.main')


@section('body')

@include('partials.card-header', ['title' => 'Create Account'])


@include('partials.success-error-notification')

<div class="row">
	<div class="col-lg-12 d-flex justify-center ">
		<div class="col-lg-6 grid-margin stretch-card offset-lg-3">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" action="/accounts" method="POST">
						@csrf
						<div class="form-group">
							<label>Name</label>
							<input type="text" class="form-control" name="name">
						</div>
						<div class="form-group">
							<label>Email address</label>
							<input type="email" class="form-control" name="email">
						</div>
						<div class="form-group">
							<label>Password</label>
							<input type="password" class="form-control" name="password">
						</div>
						<div class="form-group">
							<label>Image upload</label>
							<input type="file" name="img[]" class="file-upload-default">
							<div class="input-group col-xs-12">
								<input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
								<span class="input-group-append">
									<button class="file-upload-browse btn btn-secondary" type="button">Upload</button>
								</span>
							</div>
						</div>
						<div class="form-group">
							<label>User roles</label>
							<select class="form-control" name="role">
								<option value="super-admin">Super-admin</option>
								<option value="sub-admin">Sub-admin</option>
								<option value="customer">Customer</option>
							</select>
						</div>

<div class="mt-3">
						<button type="submit" class="btn btn-primary mr-2">Submit</button>
						<a class="btn btn-light" href="{{route('accounts.index')}}">Cancel</a>
					</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

laravel/resources/views/pages/accounts/edit.blade.php
@extends('template.main')


@section('body')

@include('partials.card-header', ['title' => 'Edit Account'])


@include('partials.success-error-notification')

<div class="row">
	<div class="col-lg-12 d-flex justify-center ">
		<div class="col-lg-6 grid-margin stretch-card offset-lg-3">
			<div class="card">
				<div class="card-body">

					<form class="forms-sample"  action="{{route('accounts.update', $account->id)}}" method="POST">
						@method('PUT')
						@csrf
						<div class="form-group">
							<label>Name</label>
							<input  type="text" value="{{$account->name}}" class="form-control" name="name">
						</div>
						<div class="form-group">
							<label>Email address</label>
							<input  type="email" class="form-control" value="{{$account->email}}" name="email">
						</div>
						<div class="form-group">
							<label>Password</label>
							<input type="password"  class="form-control" name="password">
						</div>
						<div class="form-group">
							<label>Image upload</label>
							<input type="file" name="img[]" class="file-upload-default">
							<div class="input-group col-xs-12">
								<input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
								<span class="input-group-append">
									<button class="file-upload-browse btn btn-secondary" type="button">Upload</button>
								</span>
							</div>
						</div>
						<div class="form-group">
							<label>User roles</label>
							<select class="form-control" name="role">
								<option value="super-admin" {{$account->getRoleNames()->first() == 'super-admin' ? 'selected':'' }}>Super-admin</option>
								<option value="sub-admin" {{$account->getRoleNames()->first() == 'sub-admin' ? 'selected':'' }}>Sub-admin</option>
								<option value="customer" {{$account->getRoleNames()->first() == 'customer' ? 'selected':''}}>Customer</option>
							</select>
						</div>

						<div class="mt-3">
							<button type="submit" class="btn btn-primary mr-2">Submit</button>
							<a href="{{route('accounts.index')}}" class="btn btn-light">Cancel</a>
						</div>
					</form>

				</div>
			</div>
		</div>
	</div>
</div>
@endsection

laravel/resources/views/pages/accounts/index.blade.php
  @extends('template.main')

  @section('body')

  @include('partials.card-header', ['title' => 'Account Lists'])

  @include('partials.success-error-notification')


  @include('partials.search-form', [ 'route' => '/accounts/search', 
  'searchKey' => [
   ['value' => 'email', 'text' => 'EMAIL'],
   ['value' => 'id', 'text' => 'USER ID'],
   ['value' => 'name', 'text' => 'USER NAME']
  ]])



  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>USER ID <a href="Javascript:void(0)" title="Click customer ID to view details"><i class="fa fa fa-id-badge text-primary"></i></a></th>
              <th>EMAIL</th>
              <th>USER NAME</th>
              <th>USER ROLE</th>
              <th>STATUS</th>
              <th>EDIT / DEACTIVATE</th>
              <th>SUSPEND / REMOVE ACCOUNT</th>
            </tr>
          </thead>
          <tbody>

            @foreach($accounts as $account)
            <tr>
              <td><a href="{{route('accounts.show', $account->id)}}" target="_blank" class="custom-link-text">{{$account->id}}</a></td>
              <td>{{$account->email}}</td>
              <td>{{$account->name}}</td>
              <td>
                <label class="badge badge-success custom-min-width-label">{{$account->getRoleNames()->first()}}</label>
              </td>
              <td>
                <label class="badge badge-success custom-min-width-label">pppp</label>
              </td>
              <td>
               <ul class="list-group custom-lists-horizontal"> 
                <li>
                  <a title="Edit account" href="{{route('accounts.edit', $account->id)}}" class="btn social-btn btn-inverse-secondary">
                    <i class="fa fa-edit text-black"></i>
                  </a>
                </li>
                <li>
                  <button type="button" title="Cancel request" class="btn social-btn btn-inverse-secondary">
                    <i class="fa fa-unlock text-black"></i>
                  </button>

                </li>
              </ul>
            </td>

            <td>
              <ul class="list-group custom-lists-horizontal"> 
                <li >
                 <button type="button" title="Cancel request" class="btn social-btn btn-inverse-secondary">
                  <i class="fa fa-gavel text-black"></i>
                </button>
              </li>
              <li>
                <button type="button" title="remove user" onclick="destroyUser('{{$account->id}}')" class="btn social-btn btn-inverse-secondary">
                  <i class="fa fa-trash-o text-black"></i>
                </button>

              </li>
            </ul>
          </td>


        </tr>
        @endforeach

      </tbody>
    </table>
    <div class="col-lg-12 my-3">
      <a href="/accounts/create" class="btn btn-primary btn-fw">Add Account</a>
    </div> 
  </div>
</div>
</div>



<script>

 const destroyUser = id => {

  if(confirm('Are you sure you want to proceed')) {
   $.ajaxSetup({
    headers: { 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content }
  })
   $.ajax({
    url: '/accounts/'+id,
    method: 'DELETE',
    data: { 
     id
   },
   success:  res => {
    alert(JSON.stringify(res.success))
    window.location.reload();
  },  
  catch : err => {
   alert(JSON.stringify(err))
 }})
 }

} 
</script>

@endsection

laravel/resources/views/pages/accounts/show.blade.php
@extends('template.main')


@section('body')

@include('partials.card-header', ['title' => 'View Account'])


@include('partials.success-error-notification')

<div class="row">
	<div class="col-lg-12 d-flex justify-center ">
		<div class="col-lg-6 grid-margin stretch-card offset-lg-3">
			<div class="card">
				<div class="card-body">
				
						<div class="form-group">
							<label>Name</label>
							<input readonly type="text" value="{{$account->name}}" class="form-control" name="name">
						</div>
						<div class="form-group">
							<label>Email address</label>
							<input readonly type="email" class="form-control" value="{{$account->email}}" name="email">
						</div>
						<div class="form-group">
							<label>Password</label>
							<input type="password" readonly class="form-control" name="password">
						</div>
						<div class="form-group">
							<label>Image upload</label>
							<input type="file" name="img[]" class="file-upload-default">
							<div class="input-group col-xs-12">
								<input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
								<span class="input-group-append">
									<button class="file-upload-browse btn btn-secondary" type="button">Upload</button>
								</span>
							</div>
						</div>
						<div class="form-group">
							<label>User roles</label>
							<select class="form-control" name="role" disabled>
								<option value="super-admin" {{$account->getRoleNames()->first() == 'super-admin' ? 'selected':'' }}>Super-admin</option>
								<option value="sub-admin" {{$account->getRoleNames()->first() == 'sub-admin' ? 'selected':'' }}>Sub-admin</option>
								<option value="customer" {{$account->getRoleNames()->first() == 'customer' ? 'selected':''}}>Customer</option>
							</select>
						</div>

				</div>
			</div>
		</div>
	</div>
</div>
@endsection