laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index');

// Route::group(['middleware' => ['auth', 'role:super-admin,sub-admin']], function () {


Route::group(['namespace' => 'AdminPanel'], function () {

Route::post('/accounts/search', 'AccountsResource@search');
Route::resource('/accounts', 'AccountsResource');

Route::get('/visits/escalated', 'VisitControllerResource@getEscalated');
Route::post('/visits/status', 'VisitControllerResource@updateStatus')->name('visits.status');
Route::resource('/visits', 'VisitControllerResource');

Route::post('/catalogs/status', 'CatalogControllerResource@updateStatus')->name('catalogs.status');

Route::post('/categories/search', 'CategoriesControllerResource@search');
Route::resource('/categories', 'CategoriesControllerResource');

Route::post('/breeds/search', 'BreedControllerResource@search');
Route::resource('/breeds', 'BreedControllerResource');

Route::resource('/catalogs', 'CatalogControllerResource');
Route::resource('/contact-details', 'ContactDetailControllerResource');



});

Route::get('/{page}', 'HomeController@page');

// });

laravel/app/Models/Breed.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Breed extends Model
{

	use Sluggable;

	protected $table = 'breeds';
	protected $fillable = ['name', 'slug'];


public function sluggable()
	{
		return [
			'slug' => [
				'source' => 'name'
			]
		];
	}
	   public function setNameAttribute($value)
    {
        $this->attributes['name'] =  Str::title($value);
    }
}

laravel/resources/views/pages/breeds/create.blade.php
	@extends('template.main')

	@section('body')

	@include('partials.card-header', ['title' => 'Add Breeds'])

	@include('partials.success-error-notification')

	<div class="row">
		<div class="col-lg-12 d-flex justify-center ">
			<div class="col-lg-4 grid-margin stretch-card mx-auto">
				<div class="card">
					<div class="card-body">

						<form class="forms-sample" action="{{route('breeds.store')}}" method="POST">
							@csrf
							<div class="form-group">
								<label >Breed Name</label>
								<input type="text" name="name" class="form-control" autofocus>
							</div>

							<div class="mt-5">
								<button type="submit" class="btn btn-primary mr-2">Submit</button>
								<a href="{{route('breeds.index')}}" class="btn btn-light">Cancel</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	@endsection

laravel/resources/views/pages/breeds/edit.blade.php
	@extends('template.main')

	@section('body')

	@include('partials.card-header', ['title' => 'Edit Breed'])

	@include('partials.success-error-notification')

	<div class="row">
		<div class="col-lg-12 d-flex justify-center ">
			<div class="col-lg-4 grid-margin stretch-card mx-auto">
				<div class="card">
					<div class="card-body">

						<form class="forms-sample" action="{{route('breeds.update', $model->id)}}" method="POST">
							@method('PUT')
							@csrf
							<div class="form-group">
								<label >Breed Name</label>
								<input value="{{$model->name}}" type="text" name="breed[name]" class="form-control" autofocus>
							</div>

							<div class="mt-5">
								<button type="submit" class="btn btn-primary mr-2">Submit</button>
								<a href="{{route('breeds.index')}}" class="btn btn-light">Cancel</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	@endsection

laravel/resources/views/pages/breeds/index.blade.php
@extends('template.main')

@section('body')

@include('partials.card-header', ['title' => 'BREED LISTS'])

@include('partials.success-error-notification')

<div class="col-lg-7 mx-auto">
  <form method="POST" action="breeds/search" id="search">
    @csrf
    <div class="form-group">
      <div class="input-group">
       <input type="text" class="form-control" name="search" style="font-size: 1.2em" placeholder="Search" aria-label="Search" aria-describedby="colored-addon3">
       <div class="input-group-append bg-secondary border-primary">
        <span class="input-group-text bg-transparent">
         <a style="cursor: pointer;" onclick="document.querySelector('#search').submit()">
          <i class="fa fa-search "></i>
        </a>
      </span>
    </div>
  </div>
</div>
</form>
</div>

<div class="col-lg-7 mx-auto grid-margin stretch-card">
 <div class="card">
  <div class="card-body">
    <div class="table-responsive">
     <table class="table table-hover">
      <thead>
       <tr>
        <th>BREED NAME</th>
        <th>EDIT</th>
        <th>REMOVE</th>
      </tr>
    </thead>
    <tbody>
      @foreach($breeds as $breed)
      <tr>
        <td>{{$breed->name}}</td>
        <td> <a  href="{{route('breeds.edit', $breed->id)}}" title="mark as completed"   class="btn social-btn btn-inverse-secondary">
          <i class="text-black fa fa-edit"></i>
        </a></td>
        <td>
          <a href="javascript:void(0)" onclick="destroy('{{$breed->id}}')" title="remove breed"  class="btn social-btn btn-inverse-secondary">
            <i class="fa fa-trash-o text-black"></i>
          </a>
        </td>
      </tr>
      @endforeach
    </tbody>
    <tfoot>
     <tr class="custom-pagination-space-around">
      <td><a href="/breeds/create" class="btn btn-primary btn-fw">Add Breed</a></td>
      <td  colspan="2">{{$breeds->links()}}</td> 
    </tr>
  </tfoot>

</table>
</div>
</div>
</div>
</div>



<script type="text/javascript">

 const destroy = id => {

  if(confirm('Are you sure you want to proceed')) {
   $.ajaxSetup({
    headers: { 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content }
  })
   $.ajax({
    url: '/breeds/'+id,
    method: 'DELETE',
    data: { 
     id
   },
   success:  res => {
    alert(JSON.stringify(res.success))
    window.location.reload();
  },  
  catch : err => {
   alert(JSON.stringify(err))
 }})
 }

} 


</script>





@endsection