laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/', 'HomeController@index');

// Route::group(['middleware' => ['auth', 'role:super-admin,sub-admin']], function () {


Route::group(['namespace' => 'AdminPanel'], function () {

Route::post('/accounts/search', 'AccountsResource@search');
Route::resource('/accounts', 'AccountsResource');

Route::get('/visits/escalated', 'VisitControllerResource@getEscalated');
Route::post('/visits/status', 'VisitControllerResource@updateStatus')->name('visits.status');
Route::resource('/visits', 'VisitControllerResource');

Route::post('/catalogs/status', 'CatalogControllerResource@updateStatus')->name('catalogs.status');

Route::post('/categories/search', 'CategoriesControllerResource@search');
Route::resource('/categories', 'CategoriesControllerResource');

Route::post('/breeds/search', 'BreedControllerResource@search');
Route::resource('/breeds', 'BreedControllerResource');

Route::resource('/catalogs', 'CatalogControllerResource');
Route::resource('/contact-details', 'ContactDetailControllerResource');



});

Route::get('/{page}', 'HomeController@page');

// });

laravel/app/Models/ContactDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class ContactDetail extends Model
{
	// $table->string('address')->nullable();
	// $table->string('number')->nullable();
	// $table->string('office_sched')->nullable();
	// $table->string('email')->nullable();
	protected $fillable = ['address', 'number','office_sched','email'];
	
	public function setAddressAttribute($value)
	{
		$this->attributes['address'] =  Str::title($value);
	}
}

laravel/resources/views/pages/contact-details/index.blade.php
@extends('template.main')

@section('body')

@include('partials.card-header', ['title' => 'CONTACT DETAILS'])

@include('partials.success-error-notification')


<div class="col-lg-4 mx-auto">
 <div class="card p-3">
  <form method="POST" action="{{route('contact-details.store')}}">
      @csrf
   <div class="form-group"> 
    <label>Address</label>
    <textarea name="address"  value="{{$contactDetails['address']}}" class="form-control" rows="10" required></textarea>
  </div>

  <div class="form-group"> 
    <label>Email</label>
    <input type="text" class="form-control" name="email" placeholder="admin@example.com" required />
  </div> 

  <div class="form-group"> 
    <label>Office sched</label>
    <input type="text" class="form-control" name="office_sched" placeholder="Mon to Fri 9am to 6 pm" required />
  </div> 

  <div class="form-group"> 
    <label>Contact Number</label>
    <input type="text" class="form-control" name="number" placeholder="+639 272332292" required />
  </div> 
  
  <div class="mt-5 pull-right">
    <a href="{{route('contact-details.index')}}" class="btn btn-light">Cancel</a>
    <button type="submit" class="btn btn-primary mr-2">Submit</button>
  </div>
</form> 
</div>
</div>


@endsection